services:
  - type: web
    name: facas-brazao
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && flask db upgrade
    startCommand: gunicorn run:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.4
      - key: FLASK_APP
        value: run.py
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: APP_PUBLIC_URL
        sync: false
      - key: MERCADO_PAGO_ACCESS_TOKEN
        sync: false
      - key: MERCADO_PAGO_PUBLIC_KEY
        sync: false
      - key: MERCADO_PAGO_WEBHOOK_SECRET
        sync: false
    disk:
      name: uploads
      mountPath: /opt/render/project/src/app/static/uploads
      sizeGB: 1
