"""initial flask schema

Revision ID: 044724036c6a
Revises: 
Create Date: 2026-07-10 11:10:07.242658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '044724036c6a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atividades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=80), nullable=True),
    sa.Column('user_name', sa.String(length=160), nullable=True),
    sa.Column('action', sa.String(length=160), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categorias',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categorias_slug'), ['slug'], unique=True)

    op.create_table('configuracoes',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cupons',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('min_subtotal', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cupons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cupons_code'), ['code'], unique=True)

    op.create_table('produtos',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('sku', sa.String(length=120), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('promo_price', sa.Float(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('min_stock', sa.Integer(), nullable=False),
    sa.Column('badge', sa.String(length=80), nullable=True),
    sa.Column('image', sa.String(length=260), nullable=True),
    sa.Column('gallery', sa.JSON(), nullable=True),
    sa.Column('steel', sa.String(length=120), nullable=True),
    sa.Column('size', sa.String(length=80), nullable=True),
    sa.Column('handle_material', sa.String(length=160), nullable=True),
    sa.Column('weight', sa.String(length=80), nullable=True),
    sa.Column('blade_length', sa.String(length=80), nullable=True),
    sa.Column('total_length', sa.String(length=80), nullable=True),
    sa.Column('sheath', sa.String(length=160), nullable=True),
    sa.Column('production_time', sa.String(length=120), nullable=True),
    sa.Column('shipping_time', sa.String(length=120), nullable=True),
    sa.Column('warranty', sa.String(length=220), nullable=True),
    sa.Column('care', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('featured', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_produtos_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_produtos_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_produtos_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_produtos_slug'), ['slug'], unique=True)

    op.create_table('usuarios',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('guest', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_usuarios_role'), ['role'], unique=False)

    op.create_table('avaliacoes',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('product_id', sa.String(length=80), nullable=False),
    sa.Column('product_name', sa.String(length=180), nullable=False),
    sa.Column('customer_id', sa.String(length=80), nullable=False),
    sa.Column('customer_name', sa.String(length=160), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('avaliacoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_avaliacoes_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_avaliacoes_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_avaliacoes_status'), ['status'], unique=False)

    op.create_table('caixa_fechamentos',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('opening_balance', sa.Float(), nullable=False),
    sa.Column('expected_balance', sa.Float(), nullable=False),
    sa.Column('counted_balance', sa.Float(), nullable=False),
    sa.Column('difference', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('closed_by', sa.String(length=80), nullable=False),
    sa.Column('closed_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['closed_by'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('caixa_lancamentos',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('method', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=240), nullable=False),
    sa.Column('created_by', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedidos',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('customer_id', sa.String(length=80), nullable=False),
    sa.Column('customer_name', sa.String(length=160), nullable=False),
    sa.Column('customer_email', sa.String(length=180), nullable=False),
    sa.Column('customer_phone', sa.String(length=40), nullable=True),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('cep', sa.String(length=12), nullable=True),
    sa.Column('payment_method', sa.String(length=80), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('shipping', sa.Float(), nullable=False),
    sa.Column('discount', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('timeline', sa.JSON(), nullable=True),
    sa.Column('shipping_quote', sa.JSON(), nullable=True),
    sa.Column('coupon', sa.JSON(), nullable=True),
    sa.Column('payment', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pedidos_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedidos_status'), ['status'], unique=False)

    op.create_table('itens_pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.String(length=80), nullable=False),
    sa.Column('product_id', sa.String(length=80), nullable=False),
    sa.Column('sku', sa.String(length=120), nullable=True),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('itens_pedido', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_itens_pedido_pedido_id'), ['pedido_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_itens_pedido_product_id'), ['product_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itens_pedido', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_itens_pedido_product_id'))
        batch_op.drop_index(batch_op.f('ix_itens_pedido_pedido_id'))

    op.drop_table('itens_pedido')
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pedidos_status'))
        batch_op.drop_index(batch_op.f('ix_pedidos_customer_id'))

    op.drop_table('pedidos')
    op.drop_table('caixa_lancamentos')
    op.drop_table('caixa_fechamentos')
    with op.batch_alter_table('avaliacoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_avaliacoes_status'))
        batch_op.drop_index(batch_op.f('ix_avaliacoes_product_id'))
        batch_op.drop_index(batch_op.f('ix_avaliacoes_customer_id'))

    op.drop_table('avaliacoes')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_role'))
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))

    op.drop_table('usuarios')
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_produtos_slug'))
        batch_op.drop_index(batch_op.f('ix_produtos_name'))
        batch_op.drop_index(batch_op.f('ix_produtos_category'))
        batch_op.drop_index(batch_op.f('ix_produtos_active'))

    op.drop_table('produtos')
    with op.batch_alter_table('cupons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cupons_code'))

    op.drop_table('cupons')
    op.drop_table('configuracoes')
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categorias_slug'))

    op.drop_table('categorias')
    op.drop_table('atividades')
    # ### end Alembic commands ###
