"""add quotes and mercado pago flow

Revision ID: 260caa74c726
Revises: 044724036c6a
Create Date: 2026-07-10 13:45:49.837781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '260caa74c726'
down_revision = '044724036c6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orcamentos',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('customer_name', sa.String(length=160), nullable=False),
    sa.Column('customer_phone', sa.String(length=40), nullable=False),
    sa.Column('customer_email', sa.String(length=180), nullable=True),
    sa.Column('knife_type', sa.String(length=120), nullable=False),
    sa.Column('main_use', sa.String(length=160), nullable=True),
    sa.Column('desired_size', sa.String(length=80), nullable=True),
    sa.Column('steel_type', sa.String(length=120), nullable=True),
    sa.Column('handle_material', sa.String(length=120), nullable=True),
    sa.Column('sheath', sa.String(length=120), nullable=True),
    sa.Column('engraving', sa.Boolean(), nullable=False),
    sa.Column('engraving_text', sa.String(length=180), nullable=True),
    sa.Column('budget_range', sa.String(length=80), nullable=True),
    sa.Column('desired_deadline', sa.String(length=80), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reference_images', sa.JSON(), nullable=True),
    sa.Column('estimated_value', sa.Float(), nullable=True),
    sa.Column('estimated_deadline', sa.String(length=80), nullable=True),
    sa.Column('admin_response', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orcamentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orcamentos_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orcamentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orcamentos_status'))

    op.drop_table('orcamentos')
    # ### end Alembic commands ###
