"""add customer favorites

Revision ID: 53cd79d890e1
Revises: 260caa74c726
Create Date: 2026-07-10 15:25:00.033373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53cd79d890e1'
down_revision = '260caa74c726'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favoritos',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.String(length=80), nullable=False),
    sa.Column('product_id', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['produtos.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'product_id', name='uq_favorito_usuario_produto')
    )
    with op.batch_alter_table('favoritos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_favoritos_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_favoritos_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favoritos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_favoritos_user_id'))
        batch_op.drop_index(batch_op.f('ix_favoritos_product_id'))

    op.drop_table('favoritos')
    # ### end Alembic commands ###
